### ISSUE TITLE
matVecMult function returns address of local variable (07-matrix-vector-mult/utils/utils.c)

### ISSUE THREAD

**Issue by regencode** [MATH6183001-Scientific-Computing-2210/basic-c#1]
![warning](https://user-images.githubusercontent.com/114067350/205044821-dbe93bca-08bf-45be-b311-e7abcac25c09.PNG)

Causes segmentation fault when main.out is executed

Compiler: gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0

**Comment by regencode** [comment]
i suggest dynamically allocating memory to vector "vo" (instead of statically):

` int *vo = (int *) malloc(N*N*sizeof(N));`

Using this, main.out executes with no problems

**Comment by ardimasp** [comment]
Totally agree. I just fixed it. Thanks!!
