### ISSUE TITLE
06-matrix-intro -> segmentation fault

### ISSUE THREAD

**Issue by regencode** [MATH6183001-Scientific-Computing-2210/basic-c#2]
![06-matrix intro](https://user-images.githubusercontent.com/114067350/205050224-d3f9f666-fc2c-48f4-a9f1-1982371f172e.PNG)

Maybe similar issue with 07-matrix-vector-mult
Compiler : gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0

**Comment by ardimasp** [comment]
If it is related to the original segmentation fault, it's already fixed. Thanks!
